project: 
  type: book
  preview: 
      port: 5678
  execute-dir: project
  # pre-render: "01_R_Files/helperfunctions.R"

lang: en

format: 
  html:
    theme:
      light: [flatly]
      dark: [flatly, aux/presenter.scss]
    highlight-style:
      light: aux/arrow-light.theme
      dark: aux/arrow-light.theme
    css: 
      - aux/custom.css
      - aux/theme-custom.scss
    bibliography: aux/bibliography.bib
    number-sections: false
    code-tools:
      source: false


execute:
  freeze: true
  error: false
  message: false
  warning: false

book:
  title: "Computational Movement Analysis: Patterns and Trends in Environmental Data"
  sidebar: 
    logo: 02_Images/zhaw_sw_pos.png
    collapse-level: 1
    style: floating
    tools: 
      - icon: easel
        href: /
  reader-mode: true
  repo-url: https://github.com/ComputationalMovementAnalysis/FS24/
  repo-actions: [edit]
  chapters:
    - index.qmd
    - Intro/1_preparations_course.qmd
    - Intro/2_preparations_project.qmd
    - part: Week 1
      chapters:
      - Week1/1_preparation.qmd
      - Week1/2_tasks_and_inputs.qmd
      - Week1/3_solutions.qmd
    - part: Week 2 
      chapters:
      - Week2/2_demo_tidyverse.qmd
      - Week2/3_exercise_a.qmd
      - Week2/3_exercise_b.qmd
      - Week2/3_exercise_c.qmd
      - Week2/4_solutions.qmd
    - part: Week 3
      chapters:
      - Week3/1_preparation.qmd
      - Week3/2_exercise_A.qmd
      - Week3/3_exercise_B.qmd
      - Week3/4_exercise_C.qmd

    - part: Week 4
      chapters:
      - Week4/1_preparation.qmd
      - Week4/1_input.qmd
      - Week4/2_tasks_and_inputs.qmd
      - Week4/2_tasks_B.qmd
      # - Week4/3_solutions.qmd
    - part: Week 5
      chapters:
      - Week5/1_preparation.qmd
      - Week5/2_demo.qmd
      - Week5/2_tasks_and_inputs.qmd
      # - Week4/3_solutions.qmd
    - part: Week 6
      # chapters:
      # - Week6/1_preparation.qmd
      # - Week6/2_tasks_and_inputs.qmd
      # - Week5/3_solutions.qmd
    - 90_references.qmd
    - Appendix/Appendix.qmd

