# Preparation Project {#sec-preperation-project}

As your course assignment (Leistungsnachweis) you will develop a semester project, in groups of two. In this semester project you will analyze trajectory data of movement activities (e.g. biking, hiking, running, shopping). 

In fact, we give you the opportunity to track your own movement behavior, generating trajectory data you will subsequently analyze yourself. There are two ways for you to generate your own trajectory data. 

<!-- During the course, we will give you the opportunity to share your data with the other students in the course, so that the shared data pool for all can grow. -->

Please let us know which option you choose by filling out the following [survey](https://moodle.zhaw.ch/mod/choice/view.php?id=1192128) on Moodle.

## Option 1: Tracking App

By using a tracking app, your phone will collect your movement data automatically. There are different types of tracking apps, from tracking specific activities to passivly tracking 24 hours. Here is a not conclusive list of tracking tools you could use. But fill free to use your own tracking tool if you are already using one:

::: {#tbl-data-collection}

```{r}
#| echo: false
library("readr")
library("kableExtra")
library("dplyr")

data_collection <- read_csv("./data-collection.csv")

data_collection |>
    mutate(
        across(-c(Name, `Tracking Type`), \(x) ifelse(x == "NA", "", cell_spec("Link", "html", link = x)))
    ) |>
    kable(format = "html", escape = FALSE) |>
    kable_styling(full_width = TRUE) |>
    column_spec(1, width_min = "10em")
```

Tracking Methods

:::

Please check after a view days if the tracking is working properly. If you have any issues during installation or you are not able to track yourself after the installtion please get in contact with [Nils](mailto:rata@zhaw.ch) or [Dominic](mailto:luoe@zhaw.ch).

***If, however, for privacy reasons, you dont want to use a Tracking App we can hand out a GPS tracker to you.***

## Option 2: GPS Tracker 

You can use a GPS tracker, provided by our research group. By using a GPS tracker all your data will stay with you locally. 

The drawback off this option is, that in order to retreave the data, you need to bring the tracker to us. Also more manual preprocessing is necessary when preparing your data for the project.

If you choose this option please send us a quick [E-Mail](mailto:luoe@zhaw.ch) so we can arrange the handover of the GPS tracker. You can get the tracker in our office GC 134 at the [Campus Grüental, Wädenswil](https://goo.gl/maps/xDvGFMBEvwBMdWiz7).